# AutoGroup config
# Promotion command.
# %1$s == glayername
# %2$s == group
command: permissions player setgroup %1$s %2$s

# The interval between checking players times
interval: 60

# The defined auto promote groups
# format is NAME: TIME (seconds)
groups:
