debug: true

# MYQL Database Information
mysqlURL: 127.0.0.1
dbName: AutoGroup
username: AutoGroup
password: AutoGroup

# Internal Table Structure - Do not change!
table: donators
table2: players

# Set to true if players belong to more than 1 group
addGroup: false

# Promotion command.
# %1$s == glayername
# %2$s == group
command: permissions player setgroup %1$s %2$s

# The interval between checking players times
interval: 60

# Loyalty Information
loyaltyGroup: Whitelist
loyaltyTime: 2678400

# Donation Information
don1Group: Don1
don2Group: Don2
don3Group: Don3
don1Amount: 15
don2Amount: 25
don3Amount: 26

addict1Group: Addict1
addict2Group: Addict2
addict3Group: Addict3
addict1Amount: 3600
addict2Amount: 36000
addict3Amount: 360000