name: AutoGroup
version: 2.0
description: Bukkit plugin to automatically group users based on the time they have spent online and donation amounts.
author: md_5
website: https://github.com/md-5/AutoGroup-Time

main: com.md_5.autogroup.time.AutoGroup

commands:
  playtime:
    description: View how long a player has been playing for, time until next rank, and if allowed, ability to change that time
    aliases: play
    permission: autogroup.playtime

permissions:
    autogroup.playtime:
        description: Allows use of the playtime command
        default: true
    autogroup.playtime.others:
        description: Allows use of the playtime command on others
        default: op
    autogroup.playtime.settime:
        description: Allows setting how long a player has played for
        default: op
    autogroup.norank:
        description: Prevents player from being ranked
        default: op
